SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE `User` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `Media` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `Tag` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `Media_Tags` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `Review` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `Comment` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `Like` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `Follow` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `List` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE `List_Items` MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS=1;